### ISSUE TITLE
[BUG] Vanilla underwater mobs not  spawning

### ISSUE THREAD

**Issue by aniket-patil-dev** [Minecraft-Eternal/MC-Eternal-1.12#117] opened 2021-04-22 08:05 UTC
I'm playing on version 1.4.3.1 and squids and other mobs don't seem to spawn

**Comment by cornehoskam** [comment] 2021-05-14 08:09
Duplicate of https://github.com/Minecraft-Eternal/MC-Eternal-1.12/issues/115

**Closed as completed by cornehoskam** 2021-05-14 08:09 UTC
Labels: bug, duplicate
