### ISSUE TITLE
[BUG] I don't know if this is a bug or some mod, but every time I die I lose all my items (they are not even dropped) I am not in hardcore and I have the keep inventory true . I am in 1.4.4 version

### ISSUE THREAD

**Issue by cozmineo** [Minecraft-Eternal/MC-Eternal-1.12#203] opened 2021-05-31 18:29 UTC
**Describe the bug**

**Version of MC Eternal**
Which version of the mod pack are you on?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by criscky** [comment] 2021-06-01 13:32
i cant reproduce this error, gonna need more information

**Comment by cozmineo** [comment] 2021-06-01 19:57
the items are simply disappearing, they are not even dropped.  Every time I die the items are still in the inventory and when I respawn I lose all my items

**Comment by criscky** [comment] 2021-06-01 20:36
try remove keepinventory
also did you added or removed any mod to the pack? or change any config?

**Comment by cozmineo** [comment] 2021-06-01 20:44
yeah i have added other mods to modpack , but i will try to take the keep inventory .  thanksssss

**Comment by criscky** [comment] 2021-06-02 12:09
if you have the problem without any modification on the pack make a new issue, i'll close this one

**Closed as completed by criscky** 2021-06-02 12:09 UTC
Labels: NonMCE, Cannot Reproduce
