### ISSUE TITLE
[BUG] Describe the bug in a single sentence

### ISSUE THREAD

**Issue by M-T-Rod** [Minecraft-Eternal/MC-Eternal-1.12#344] opened 2021-08-31 15:52 UTC
**Describe the bug**
Being on the moon crashes server my is on. Problem is known on the internet.

**Version of MC Eternal**
1.4.4 

**To Reproduce**
Wander arround the moon with your map being on server.

**Expected behavior**
Server not crashing ?

**Comment by criscky** [comment] 2021-08-31 18:12
duplicate of #160

**Closed as completed by criscky** 2021-08-31 18:12 UTC
Labels: duplicate
